[package]
org = "bal_workshop"
name = "book_service"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "book_service"
options.datastore = "inmemory"
filePath = "persist/model.bal"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.3.0"

